redis = "12808"

[train]
resume = false
epoch = 1
output_dir = "./outputs/qwen3-moe-30b-tp4-r-tp2-grpo-fp8"
epsilon = 1e-6
optm_name = "AdamW"
optm_lr = 1e-6
optm_impl = "foreach"
optm_weight_decay = 0.0
optm_betas = [0.9, 0.999]
optm_warmup_steps = 20
optm_grad_norm_clip = 1.0
async_tp_enabled = false
compile = false
param_dtype = "bfloat16"
fsdp_reduce_dtype = "float32"
fsdp_offload = false
fsdp_reshard_after_forward = "default"
train_batch_per_replica = 2
sync_weight_interval = 1

[train.fp8]
enable_fp8 = true
fp8_recipe = "dynamic_scaling"
quant_recipe = "rowwise"
fqn_filter=["lm_head"]

[rollout]
gpu_memory_utilization = 0.7
enable_chunked_prefill = false
max_response_length = 512 
n_generation = 16
batch_size = 1
quantization = "none"
seed = 42

[policy]
model_name_or_path = "Qwen/Qwen3-30B-A3B"
model_max_length = 512 
model_gradient_checkpointing = true

[logging]
logger = ['console', 'wandb']
project_name = "cosmos_rl"
experiment_name = "None"

[train.train_policy]
type = "grpo"
dataset.name = "JiaxinTsao/math_examples"
prompt_column_name = "prompt"
response_column_name = "result"
reward_function = "boxed_math"
dataset.split = "train"
temperature = 0.9
epsilon_low = 0.2
epsilon_high = 0.2
kl_beta = 0.0
mu_iterations = 1
min_filter_prefix_tokens = 1
mini_batch = 1

[train.ckpt]
enable_checkpoint = true
save_freq = 20
save_mode = "async"

[rollout.parallelism]
n_init_replicas = 1
tp_size = 2
pp_size = 1

[rollout.sampling_config]
temperature = 0.9
top_p = 1.0
top_k = 10

[policy.parallelism]
n_init_replicas = 1
tp_size = 4
cp_size = 1
dp_shard_size = 1
pp_size = 1
dp_replicate_size = 1

